#!/bin/bash

BASEDIR=$(readlink -f "$0" | xargs dirname)

function bookmarksAsJson {
	buku -p -j
}

function jsonToLine {
	"$BASEDIR"/jsonToLine.jq
}

function formatColumns {
	"$BASEDIR"/format-columns.awk
}

function searchAsYouType {
	peco --prompt "$MODE:" --null
}

function openInBrowser {
	while read -r selectedUrlAndIndex; do
		selectedUrl=${selectedUrlAndIndex%|*}
		xdg-open "$selectedUrl"
	done
}

function searchAndSelectBookmarks {
	bookmarksAsJson |
	jsonToLine |
	formatColumns |
	searchAsYouType
}

function askUserForTag {
	read -r -p "input the tag to add: " tag
	echo "$tag"
}

function tagBookmarkAtIndex {
	index=$1
	tag=$2
	buku --update "$index" --tag "$tag"
}

function tagBookmarks {
	urlsAndIndices=(`searchAndSelectBookmarks`)
	tag=$(askUserForTag)
	for urlAndIndex in "${urlsAndIndices[@]}"; do
		index="${urlAndIndex#*|}"
		tagBookmarkAtIndex "$index" "$tag"
	done
}

function openBookmarks {
	searchAndSelectBookmarks | openInBrowser
}

# set default mode
MODE="open"
BADARGERROR='loin error: invalid argument, for now the only valid argument is the flag "--tag"'

# parse tag mode command line flag, throw error in invalid input
if [[ "$1" == "--tag" ]]; then
	MODE="tag"
elif [[ -n "$1" ]]; then
	echo "$BADARGERROR"
	exit 1
fi

# run
if [[ "$MODE" == "open" ]]; then
	openBookmarks
elif [[ "$MODE" == "tag" ]]; then
	tagBookmarks
fi
